### ISSUE TITLE
Big Sur: bad CPU type in executable: ocr

### ISSUE THREAD

**Issue by wzes** [schappim/macOCR#11]
zsh: bad CPU type in executable: ocr
![image](https://user-images.githubusercontent.com/19406071/119615754-52b26f80-be32-11eb-8cf3-b4cda3436511.png)

**Comment by Tangjiandd** [comment]
use intel repo

**Comment by schappim** [comment]
If you're on intel, use the latest test version: https://files.littlebird.com.au/ocr-XynT9NApdOnkqeCYrkLxJOHcjFpi.zip

**Comment by jackwu882002** [comment]
got it right
