### ISSUE TITLE
cp: ocr: No such file or directory

### ISSUE THREAD

**Issue by weiwentao518** [schappim/macOCR#13]
![image](https://user-images.githubusercontent.com/28976633/122715307-3ff95200-d29b-11eb-9407-46de58516bc9.png)

**Comment by schappim** [comment]
You might want to read the output: 

![Untitled 2](https://user-images.githubusercontent.com/40018/122715542-5d82e780-d2ac-11eb-877b-e20b0a7d7cbd.png)
