### ISSUE TITLE
is this version work for macOS Big Sur

### ISSUE THREAD

**Issue by lixin-meng** [schappim/macOCR#14]
Followed the installation. But it always return empty string, even with the T-shirt example in the README

**Comment by ww7** [comment]
1. Check if you allowed it in permissions ![](https://cln.sh/4nAsoY)
2. Do you download correct binary?

**Comment by lixin-meng** [comment]
yes, and yes

**Comment by schappim** [comment]
You might also need to give your terminal permissions.
