### ISSUE TITLE
Can't unzip (Intel / Catalina)

### ISSUE THREAD

**Issue by assadtony** [schappim/macOCR#18]
Running on a Intel / Catalina (2.6 GHz 6-Core Intel Core i7)
```
curl -O https://files.littlebird.com.au/ocr.zip; 
unzip ocr.zip;
sudo cp ocr /usr/local/bin;
```

And I am getting that it can't unzip the file to get the binaries
![image](https://user-images.githubusercontent.com/1627323/135361307-6c969b60-286e-4390-9191-0bdcd4807922.png)

Any suggestions as to what I might be doing wrong?

**Comment by schappim** [comment]
Just remove this:
https://files.littlebird.com.au/Shared-Image-2021-09-30-17-28-38-4JoGSsokVrQkqB9oelBiZgZ6MGaz.png

Cheers,

Marcus

**Comment by assadtony** [comment]
Worked, thanks!
