### ISSUE TITLE
Alfred workflow: `brew` is installed to /opt/homebrew

### ISSUE THREAD

**Issue by notDavid** [schappim/macOCR#22]
Minor issue, but fyi, on M1 Macs brew is installed to `/opt/homebrew` (not `/usr/local`) which prevents the Alfred workflow from executing...

So the bash script should execute: `/opt/homebrew/bin/ocr;`

You might want to change that in the Workflow :-)

**Comment by schappim** [comment]
Thanks @notDavid . This has been fixed up :)
