### ISSUE TITLE
Distribute as an App

### ISSUE THREAD

**Issue by specter78** [schappim/macOCR#3]
Hi,

Are there any plans to distribute this as an app?

**Comment by andrewcrook** [comment]
I would suggest adding it to homebrew

**Comment by jaklan** [comment]
Not sure if it's working, but worth checking:
https://github.com/sveinbjornt/Platypus

I can help with creating homebrew cask then, already done a few updates + one from scratch for:
https://github.com/jwhamilton99/menu-bar-splitter
but if you decide to distribute just pure binaries - then unfortunately I haven't played with homebrew formulae yet (it seems to be a bit more complicated than casks, but doable though 😉).

**Comment by argan** [comment]
> Not sure if it's working, but worth checking:
> https://github.com/sveinbjornt/Platypus
> 
> I can help with creating homebrew cask then, already done a few updates + one from scratch for:
> https://github.com/jwhamilton99/menu-bar-splitter
> but if you decide to distribute just pure binaries - then unfortunately I haven't played with homebrew formulae yet (it seems to be a bit more complicated than casks, but doable though 😉).

Platypus works very well.

**Comment by schappim** [comment]
Now available as: 

`brew install schappim/ocr/ocr`
