### ISSUE TITLE
OCR not worked in the terminal but work with shortcut 

### ISSUE THREAD

**Issue by noahlias** [schappim/macOCR#36]
I use ocr in the kitty terminal.
![image](https://github.com/schappim/macOCR/assets/3949397/51d44251-630f-46dd-99e9-cd2e6baf4435)

but it comes to the bus error ,there is the backtrace

![image](https://github.com/schappim/macOCR/assets/3949397/99493fc9-c9e3-45eb-8171-6b51484c0e6f)

my macos version
![image](https://github.com/schappim/macOCR/assets/3949397/1401b678-8727-45a5-9924-6cd088b3f9f9)

It works with ocr shortcut

**Comment by noahlias** [comment]
I founded the bug it's my env problem

just unset my DYLD_LIBRARY_PATH, it works in terminal.

**Comment by Akshat752** [comment]
The same issue can also happen if the terminal app does not have permissions to record the screen. I believe the shortcut has this permission by default.
