### ISSUE TITLE
Not work on Chinese language

### ISSUE THREAD

**Issue by kevinnerd** [schappim/macOCR#6]
Hi, it seems this tool can't work properly on image with Chinese language,  does it only work with English ? 
Will Chinese be supported later versions ?

**Comment by Tatsh** [comment]
Modify line 52 of `main.swift` to have:

```swift
request.recognitionLanguages = ["zh", "en"]
```

Then it will work.

**Comment by schappim** [comment]
Hi Kevin, 

Thanks for your email!

The underlying API can support both Traditional and Simplified Chinese characters. 

Could you please let me know what the output of [this script](https://files.littlebird.com.au/get_lang-hUI62JphzRJ4OdZ4ATQDmo8KpJhp.swift) is: 

```swift
#!/usr/bin/swift

import Foundation
let locale = NSLocale.autoupdatingCurrent

let code = locale.languageCode!
let language = locale.localizedString(forLanguageCode: code)!

print("\(code)")
print("\(language)")
```

We can then set the recognitionLanguages based on the output.

**Comment by ashen-zhao** [comment]
> Modify line 52 of `main.swift` to have:
> 
> ```swift
> request.recognitionLanguages = ["zh", "en"]
> ```
> 
> Then it will work.

That's good. It works

**Comment by ashen-zhao** [comment]
> Modify line 52 of `main.swift` to have:
> 
> ```swift
> request.recognitionLanguages = ["zh", "en"]
> ```
> 
> Then it will work.

> 很不错，这个可以生效，注意：替换ocr文件后， 需要再次执行`sudo cp ocr /usr/local/bin;`，才会生效

**Comment by self-made-boy** [comment]
> ```swift
> import Foundation
> let locale = NSLocale.autoupdatingCurrent
> 
> let code = locale.languageCode!
> let language = locale.localizedString(forLanguageCode: code)!
> 
> print("\(code)")
> print("\(language)")
> ```

zh
中文
locale: Locale = {}
code: String = "zh"
language: String = "中文"

**Comment by h0x91b** [comment]
On my system supported languages right now:

![Screen Shot 2021-05-24 at 23 53 48](https://user-images.githubusercontent.com/810011/119406389-630c0280-bceb-11eb-913d-1cb8e8cd69c6.jpg)

So maybe you will need to put full locale name e.g. `zh-Hans` or `zh-Hant`

BTW here the snippet to retrieve supported languages:

```
var possibleLanguages: Array<String> = []
let revision = VNRecognizeTextRequest.currentRevision

do {
    possibleLanguages = try VNRecognizeTextRequest.supportedRecognitionLanguages(for: .accurate,
                                                                            revision: revision)
} catch {
    print("Error getting the supported languages.")
}
```

**Comment by schappim** [comment]
I'm trying to test with additional languages enabled. 
I am based in Australia and for possibleLanguages, I'm only getting back `en-US`. 

I have enabled additional languages in the Language & Region settings (and rebooted). 
![image of macOS 10.5 Language and Region preferences](https://files.littlebird.com.au/Shared-Image-2021-05-25-09-47-08-t8n4zhUvFA3C6q6YgMnErSDuICPe.png)

Could this be a macOS 11 and above feature?

**Comment by schappim** [comment]
After testing on a Macbook Air w/ Big Sur, I can confirm this is a feature only available to macOS 11 and above.

**Comment by h0x91b** [comment]
Supported languages not related to `Language & Region` settings. This depends on the `revision` of the `Vision` framework...

**Comment by schappim** [comment]
@h0x91b , you of course are right!

I was testing on Catalina, and it works fine on Big Sur.

We might still want to use the Language & Region to set the recognitionLanguages sort order.

**Comment by Tatsh** [comment]
I'd like to see a command line option for the languages too.

**Comment by schappim** [comment]
Please test with ARM: https://files.littlebird.com.au/ocr.zip

**Comment by schappim** [comment]
Please test with Intel Version: https://files.littlebird.com.au/ocr-XynT9NApdOnkqeCYrkLxJOHcjFpi.zip

Please note that the Chinese Support required Big Sur.

**Comment by iczrac** [comment]
> Modify line 52 of `main.swift` to have:
> 
> ```swift
> request.recognitionLanguages = ["zh", "en"]
> ```
> 
> Then it will work.

how to open this?

**Comment by ww7** [comment]
Please share list of supported languages and add CLI parameter to check version

**Comment by schappim** [comment]
["en-US", "fr-FR", "it-IT", "de-DE", "es-ES", "pt-BR", "zh-Hans", "zh-Hant"]

**Comment by chenzz** [comment]
meet same problem.

**Comment by DemoorBug** [comment]
Bigsur 11.6 Chinese mess

**Comment by schappim** [comment]
I can confirm working with ZH: 

https://files.littlebird.com.au/Screen-Recording-2021-11-10-14-06-39.mp4
