### ISSUE TITLE
not working on big sur

### ISSUE THREAD

**Issue by jappre** [schappim/macOCR#8]

**Comment by schappim** [comment]
macOCR very much works on Big Sur.
Could you please provide us with more information on what you've tried, and what is happening?

**Comment by h0x91b** [comment]
![Screen Shot 2021-05-25 at 11 37 31](https://user-images.githubusercontent.com/810011/119466757-9c755a00-bd4d-11eb-9d86-52f55078b856.jpg)

Works fine.

**Comment by Tangjiandd** [comment]
![image](https://user-images.githubusercontent.com/18570393/119758120-965fb480-bed8-11eb-9840-7df26dfced9c.png)
