### ISSUE TITLE
Request to support Chinese Simplified

### ISSUE THREAD

**Issue by jsmjsm** [schappim/macOCR#9]
macOCR is a great tool, I hope I can use it to OCR Chinese Simplified content.

**Comment by Mu7Wind** [comment]
+1

**Comment by schappim** [comment]
I've just built a test release: 

Apple Silicon: https://files.littlebird.com.au/ocr.zip
Intel: https://files.littlebird.com.au/ocr-XynT9NApdOnkqeCYrkLxJOHcjFpi.zip

Example usage: 

```
ocr -l zh-Hans
```

**Comment by Tangjiandd** [comment]
killed     ocr -l zh-Hans

**Comment by schappim** [comment]
@Tangjiandd Could you please use more words to describe the issue? I don't mind if they're in your local language.

**Comment by Tangjiandd** [comment]
when I use the command "ocr -l zh-Hans", it present "killed ocr -l zh-Hans"

![image](https://user-images.githubusercontent.com/18570393/119758159-a9728480-bed8-11eb-97fd-67a1be0a9270.png)

**Comment by leon900415** [comment]
> I've just built a test release:
> 
> Apple Silicon: https://files.littlebird.com.au/ocr.zip
> Intel: https://files.littlebird.com.au/ocr-XynT9NApdOnkqeCYrkLxJOHcjFpi.zip
> 
> Example usage:
> 
> ```
> ocr -l zh-Hans
> ```

It doesn't work, it's still a messy code

**Comment by schappim** [comment]
@leon900415 thank you for your feedback. I am not a swift developer by trade.

It is challenging to meet your needs with "It doesn't work".

Perhaps you could provide information about your setup: 

- device, make, model, chipset
- operating system version
- locale 
- could this be a gate keeper thing?

etc

**Comment by jackwu882002** [comment]
> I've just built a test release:
> 
> Apple Silicon: https://files.littlebird.com.au/ocr.zip
> Intel: https://files.littlebird.com.au/ocr-XynT9NApdOnkqeCYrkLxJOHcjFpi.zip
> 
> Example usage:
> 
> ```
> ocr -l zh-Hans
> ```

done and cool

**Comment by schappim** [comment]
zh-Hans now supported
